name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Substitute the Manifest and Download URLs in the module.json
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: devops-actions/variable-substitution@v1.2
      with:
        files: 'module.json'
      env:
        version: ${{ github.event.release.tag_name }}
        url: https://github.com/${{ github.repository }}
        manifest: https://github.com/${{ github.repository }}/releases/latest/download/module.json
        download: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/bsa-starwarsffg.zip

    # Create a zip file with all files required by the module to add to the release
    - run: zip -r ./bsa-starwarsffg.zip module.json src/ lang/

    # Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: ${{ github.event.release.name }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json, ./bsa-starwarsffg.zip'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}
